//! egui application: top transport bar + tabbed chord-chart / staff / tab views.

use std::cell::RefCell;
use std::rc::Rc;

use crate::audio::{AudioEngine, Parts, PRESETS};
use crate::library::{self, LibEntry, LibInbox};
use leadsheet::{self as parser, Song, TICKS_PER_BAR};
use crate::notation;
use egui::{Color32, RichText};

#[derive(PartialEq, Clone, Copy)]
enum View {
    Chart,
    Staff,
    Tab,
}

type Inbox = Rc<RefCell<Option<(String, Vec<u8>)>>>;

pub struct App {
    song: Option<Song>,
    file_name: String,
    audio: Option<AudioEngine>,
    inbox: Inbox,
    view: View,
    tempo_factor: f32,
    parts: Parts,
    vol_master: f32,
    vol_melody: f32,
    vol_chords: f32,
    vol_bass: f32,
    show_chords: bool,
    show_library: bool,
    library: Vec<LibEntry>,
    library_inbox: LibInbox,
    library_loaded: bool,
    library_search: String,
    library_sort_tempo: bool,
    /// (id, edit buffer) when renaming a library entry.
    renaming: Option<(f64, String)>,
    /// Raw bytes of the currently-loaded song (so it can be saved to the library).
    current_bytes: Option<Vec<u8>>,
    playing: bool,
    /// egui time of the last seek, to debounce rapid chord clicks.
    last_seek_t: f64,
    /// Play a one-bar drum count-in before the song starts (like BiaB).
    count_in: bool,
    error: Option<String>,
}

/// Bundled demo: an ORIGINAL royalty-free progression, generated by the encoder
/// (`cargo run -p leadsheet --example gen`). No copyrighted content.
const DEMO: &[u8] = include_bytes!("../demo.mgu");

impl App {
    pub fn new(_cc: &eframe::CreationContext<'_>) -> Self {
        let mut app = Self {
            song: None,
            file_name: String::new(),
            audio: None,
            inbox: Rc::new(RefCell::new(None)),
            view: View::Chart,
            tempo_factor: 1.0,
            parts: Parts::default(),
            vol_master: 0.9,
            vol_melody: 1.0,
            vol_chords: 0.8,
            vol_bass: 0.9,
            show_chords: true,
            show_library: false,
            library: Vec::new(),
            library_inbox: Rc::new(RefCell::new(None)),
            library_loaded: false,
            library_search: String::new(),
            library_sort_tempo: false,
            renaming: None,
            current_bytes: None,
            playing: false,
            last_seek_t: 0.0,
            count_in: false,
            error: None,
        };
        // Load the bundled original demo so the app isn't empty on first run.
        if let Ok(s) = parser::parse(DEMO) {
            app.song = Some(s);
            app.file_name = "Démo libre (.MGU)".into();
            app.current_bytes = Some(DEMO.to_vec());
        }
        app
    }

    fn load_bytes(&mut self, name: String, bytes: Vec<u8>) {
        match parser::parse(&bytes) {
            Ok(s) => {
                self.song = Some(s);
                self.file_name = name;
                self.current_bytes = Some(bytes);
                self.error = None;
                if let Some(a) = &mut self.audio {
                    a.stop();
                }
                self.playing = false;
                // Play at the file's own tempo: reset the speed factor to 100 %.
                self.tempo_factor = 1.0;
            }
            Err(e) => self.error = Some(format!("« {name} » : {e}")),
        }
    }

    /// Import dropped files: load the first into the view, save them all to the
    /// library (if available).
    fn import_files(&mut self, files: Vec<(String, Vec<u8>)>, ctx: &egui::Context) {
        let lib = library::available();
        for (i, (name, bytes)) in files.into_iter().enumerate() {
            if let Ok(song) = parser::parse(&bytes) {
                if lib {
                    let key = format!(
                        "{}{}",
                        parser::pitch_class_name(song.key_pc),
                        if song.key_minor { "m" } else { "" }
                    );
                    library::save_song(
                        name.clone(),
                        bytes.clone(),
                        song.title.clone(),
                        key,
                        song.tempo_bpm,
                        song.style.clone(),
                        self.library_inbox.clone(),
                        ctx.clone(),
                    );
                }
                if i == 0 {
                    self.load_bytes(name, bytes);
                }
            }
        }
    }

    fn ensure_audio(&mut self) {
        if self.audio.is_none() {
            self.audio = AudioEngine::new();
            if self.audio.is_none() {
                self.error = Some("Web Audio indisponible dans ce navigateur.".into());
            }
        }
    }

    fn apply_volumes(&self) {
        if let Some(a) = &self.audio {
            a.set_master_gain(self.vol_master);
            a.set_part_gains(self.vol_melody, self.vol_chords, self.vol_bass);
        }
    }

    fn play(&mut self) {
        self.ensure_audio();
        self.apply_volumes();
        let factor = self.tempo_factor;
        let parts = self.parts;
        let count_in = self.count_in;
        if let (Some(a), Some(song)) = (&mut self.audio, &self.song) {
            if !a.is_scheduled() {
                a.schedule(song, factor, &parts, 0, count_in);
            }
            a.resume();
            self.playing = true;
        }
    }

    fn pause(&mut self) {
        if let Some(a) = &self.audio {
            a.suspend();
        }
        self.playing = false;
    }

    fn stop(&mut self) {
        if let Some(a) = &mut self.audio {
            a.stop();
        }
        self.playing = false;
    }

    /// Seek to a tick and start playing from there (chord-chart click).
    fn seek_to_tick(&mut self, tick: u32) {
        self.ensure_audio();
        self.apply_volumes();
        let factor = self.tempo_factor;
        let parts = self.parts;
        if let (Some(a), Some(song)) = (&mut self.audio, &self.song) {
            a.schedule(song, factor, &parts, tick, false);
            a.resume();
            self.playing = true;
        }
    }

    /// Rebuild the schedule after an option change WITHOUT losing the current
    /// playback position (tempo / instrument / part toggle).
    fn reschedule_keep_pos(&mut self) {
        let factor = self.tempo_factor;
        let was_playing = self.playing;
        let parts = self.parts;
        if let (Some(a), Some(song)) = (&mut self.audio, &self.song) {
            if a.is_scheduled() {
                let pos = a.position_ticks();
                a.schedule(song, factor, &parts, pos, false);
                if was_playing {
                    a.resume();
                } else {
                    a.suspend();
                }
            }
        }
    }
}

/// One part's on/off toggle plus an instrument dropdown.
fn instrument_part(
    ui: &mut egui::Ui,
    label: &str,
    id: &str,
    on: &mut bool,
    instr: &mut usize,
    changed: &mut bool,
) {
    if ui.checkbox(on, label).changed() {
        *changed = true;
    }
    let enabled = *on;
    ui.add_enabled_ui(enabled, |ui| {
        egui::ComboBox::from_id_salt(id)
            .selected_text(PRESETS[(*instr).min(PRESETS.len() - 1)].name)
            .show_ui(ui, |ui| {
                for (i, p) in PRESETS.iter().enumerate() {
                    if ui.selectable_value(instr, i, p.name).changed() {
                        *changed = true;
                    }
                }
            });
    });
}

/// Map a 0-based absolute playback bar onto the chart bar, accounting for the
/// intro (played once), the chorus (repeated `choruses` times) and the ending.
fn chart_bar(abs_bar0: u16, s: &Song) -> u16 {
    let cb = s.chorus_begin.max(1);
    let ce = s.chorus_end.max(cb);
    let intro = cb - 1;
    let clen = (ce - cb + 1).max(1);
    let choruses = s.choruses.max(1);
    if abs_bar0 < intro {
        return abs_bar0 + 1;
    }
    let after = abs_bar0 - intro;
    let total_chorus = clen * choruses;
    if after < total_chorus {
        return cb + (after % clen);
    }
    (ce + 1 + (after - total_chorus)).min(s.form_bars.max(ce))
}

/// Index of the chord active at the given playback position (mapped to form).
fn active_chord(s: &Song, current_bar: u16, current_tick: u32) -> Option<usize> {
    if s.chords.is_empty() {
        return None;
    }
    let beat_tick = current_tick % TICKS_PER_BAR;
    let form_tick = (current_bar.saturating_sub(1) as u32) * TICKS_PER_BAR + beat_tick;
    s.chords
        .iter()
        .enumerate()
        .rev()
        .find(|(_, c)| c.tick <= form_tick)
        .map(|(i, _)| i)
        .or(Some(0))
}

/// (root pitch-class, is_minor) for a chord, for diagram rendering.
fn chord_root_minor(c: &parser::Chord) -> (u8, bool) {
    let name = parser::pitch_class_name(c.root);
    let suffix = c.text.get(name.len()..).unwrap_or("");
    (c.root, suffix.starts_with('m'))
}

/// A compact labelled volume knob (0–150 %). Returns true if it changed.
fn volume_slider(ui: &mut egui::Ui, label: &str, v: &mut f32) -> bool {
    let mut pct = *v * 100.0;
    let resp = ui.add(
        egui::Slider::new(&mut pct, 0.0..=150.0)
            .text(label)
            .fixed_decimals(0)
            .suffix(" %"),
    );
    if resp.changed() {
        *v = pct / 100.0;
        true
    } else {
        false
    }
}

impl eframe::App for App {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        // Create the audio context up front so the page's touch handler can
        // resume() it (mobile browsers only unlock audio inside a real gesture).
        self.ensure_audio();

        // Discreet build stamp (bottom-right) so you can tell which version a
        // device actually loaded — set by CI, "dev" for local builds.
        {
            let build = option_env!("BUILD_INFO").unwrap_or("dev");
            let r = ctx.screen_rect();
            ctx.layer_painter(egui::LayerId::new(
                egui::Order::Foreground,
                egui::Id::new("build_info"),
            ))
            .text(
                r.right_bottom() - egui::vec2(5.0, 3.0),
                egui::Align2::RIGHT_BOTTOM,
                build,
                egui::FontId::monospace(10.0),
                Color32::from_gray(95),
            );
        }

        // Drain any file picked asynchronously (file dialog OR library load).
        let pending = self.inbox.borrow_mut().take();
        if let Some((name, bytes)) = pending {
            self.load_bytes(name, bytes);
        }

        // Load the library list once on startup, then drain async updates.
        if !self.library_loaded {
            self.library_loaded = true;
            if library::available() {
                library::refresh(self.library_inbox.clone(), ctx.clone());
            }
        }
        if let Some(list) = self.library_inbox.borrow_mut().take() {
            self.library = list;
        }

        // Drag-and-drop import (one or many .MGU files at once).
        let dropped: Vec<(String, Vec<u8>)> = ctx.input(|i| {
            i.raw
                .dropped_files
                .iter()
                .filter_map(|f| f.bytes.as_ref().map(|b| (f.name.clone(), b.to_vec())))
                .collect()
        });
        if !dropped.is_empty() {
            self.import_files(dropped, ctx);
        }

        // Spacebar toggles play / pause.
        if ctx.input(|i| i.key_pressed(egui::Key::Space)) && self.song.is_some() {
            if self.playing {
                self.pause();
            } else {
                self.play();
            }
        }

        // Advance playback state.
        let mut current_tick = 0u32;
        let mut finished = false;
        if self.playing {
            if let Some(a) = &mut self.audio {
                a.pump(); // realise/prune the look-ahead window of notes
                current_tick = a.position_ticks();
                finished = a.finished();
            }
            ctx.request_repaint();
        }
        if finished {
            self.stop(); // reset so the next ▶ starts from the top
            current_tick = 0;
        }
        // Map the linear playback position onto the chart, which shows the form
        // once: intro plays, then the chorus repeats, then the ending.
        let abs_bar = (current_tick / TICKS_PER_BAR) as u16;
        let current_bar = match self.song.as_ref() {
            Some(s) if s.form_bars > 0 => chart_bar(abs_bar, s),
            _ => abs_bar + 1,
        };

        // Tick requested via a chord-chart click (applied after the UI borrow).
        let mut seek_tick: Option<u32> = None;

        // Playhead tick for the beat counter / clock in the transport row.
        let play_tick = if self.playing {
            self.audio.as_ref().map_or(0, |a| a.position_ticks())
        } else {
            0
        };

        egui::TopBottomPanel::top("bar").show(ctx, |ui| {
            ui.add_space(4.0);
            ui.horizontal_wrapped(|ui| {
                if ui.button("📂  Ouvrir .MGU / .SGU").clicked() {
                    let inbox = self.inbox.clone();
                    let ctx2 = ctx.clone();
                    wasm_bindgen_futures::spawn_local(async move {
                        if let Some(file) = rfd::AsyncFileDialog::new()
                            .add_filter("Band-in-a-Box", &["MGU", "SGU", "mgu", "sgu"])
                            .pick_file()
                            .await
                        {
                            let bytes = file.read().await;
                            *inbox.borrow_mut() = Some((file.file_name(), bytes));
                            ctx2.request_repaint();
                        }
                    });
                }
                if library::available() {
                    ui.toggle_value(&mut self.show_library, "📚 Bibliothèque");
                    // Save the currently-loaded song into the local library.
                    let can_add = self.current_bytes.is_some() && self.song.is_some();
                    if ui
                        .add_enabled(can_add, egui::Button::new("💾 Ajouter"))
                        .on_hover_text("Enregistrer dans la bibliothèque (ce navigateur)")
                        .clicked()
                    {
                        if let (Some(bytes), Some(song)) = (&self.current_bytes, &self.song) {
                            let key = format!(
                                "{}{}",
                                parser::pitch_class_name(song.key_pc),
                                if song.key_minor { "m" } else { "" }
                            );
                            library::save_song(
                                self.file_name.clone(),
                                bytes.clone(),
                                song.title.clone(),
                                key,
                                song.tempo_bpm,
                                song.style.clone(),
                                self.library_inbox.clone(),
                                ctx.clone(),
                            );
                        }
                    }
                }
                ui.separator();

                let has_song = self.song.is_some();
                ui.add_enabled_ui(has_song, |ui| {
                    if self.playing {
                        if ui.button("⏸  Pause").clicked() {
                            self.pause();
                        }
                    } else if ui.button("▶  Lecture").clicked() {
                        self.play();
                    }
                    if ui.button("⏹  Stop").clicked() {
                        self.stop();
                    }
                });
                ui.checkbox(&mut self.count_in, "Décompte")
                    .on_hover_text("Un décompte batterie de 2 mesures avant le départ, comme dans Band-in-a-Box");

                ui.separator();
                ui.label("Tempo");
                let mut pct = self.tempo_factor * 100.0;
                let resp = ui.add(
                    egui::Slider::new(&mut pct, 25.0..=200.0)
                        .suffix(" %")
                        .fixed_decimals(0),
                );
                // Update the value live, but only rebuild the audio schedule
                // when the interaction ends — rescheduling on every drag tick
                // tears down and rebuilds hundreds of voices and glitches.
                if resp.changed() {
                    self.tempo_factor = pct / 100.0;
                }
                if resp.drag_stopped() || (resp.changed() && !resp.dragged()) {
                    self.reschedule_keep_pos();
                }
                if let Some(s) = &self.song {
                    let bpm = (s.tempo_bpm as f32 * self.tempo_factor).round() as i32;
                    ui.label(format!("≈ {bpm} BPM"));

                    // Elapsed-time clock (MM:SS).
                    let actual_bpm = (s.tempo_bpm as f32 * self.tempo_factor).max(1.0) as f64;
                    let secs = play_tick as f64 * 60.0 / (leadsheet::PPQ as f64 * actual_bpm);
                    let secs = secs as u32;
                    ui.separator();
                    ui.monospace(format!("{}:{:02}", secs / 60, secs % 60));
                }
            });

            // Instrument selection — one timbre per part, à la Band-in-a-Box.
            let mut changed = false;
            ui.horizontal(|ui| {
                ui.label("🎹 Instruments :");
                instrument_part(ui, "Mélodie", "mel", &mut self.parts.melody_on, &mut self.parts.melody_instr, &mut changed);
                ui.separator();
                instrument_part(ui, "Accords", "chd", &mut self.parts.chords_on, &mut self.parts.chords_instr, &mut changed);
                ui.separator();
                instrument_part(ui, "Basse", "bas", &mut self.parts.bass_on, &mut self.parts.bass_instr, &mut changed);
            });
            if changed {
                self.reschedule_keep_pos();
            }

            // Volume mixer — live, never restarts playback.
            let mut vol_changed = false;
            ui.horizontal(|ui| {
                ui.label("🔊 Volume :");
                vol_changed |= volume_slider(ui, "Global", &mut self.vol_master);
                ui.separator();
                vol_changed |= volume_slider(ui, "Mélodie", &mut self.vol_melody);
                vol_changed |= volume_slider(ui, "Accords", &mut self.vol_chords);
                vol_changed |= volume_slider(ui, "Basse", &mut self.vol_bass);
            });
            if vol_changed {
                self.apply_volumes();
            }
            ui.add_space(4.0);
        });

        // Right-hand collapsible panel: live chord diagram(s) for the current
        // (and next) chord. Data is gathered up front to avoid borrow clashes.
        type Diag = (String, u8, bool);
        let panel_chords: Option<(Diag, Option<Diag>)> = self.song.as_ref().and_then(|song| {
            active_chord(song, current_bar, current_tick).map(|i| {
                let c = &song.chords[i];
                let (r, m) = chord_root_minor(c);
                let cur = (c.text.clone(), r, m);
                let next = song.chords.get(i + 1).map(|n| {
                    let (r2, m2) = chord_root_minor(n);
                    (n.text.clone(), r2, m2)
                });
                (cur, next)
            })
        });
        let mut collapse = false;
        egui::SidePanel::right("chord_panel")
            .resizable(true)
            .default_width(172.0)
            .width_range(150.0..=480.0)
            .show_animated(ctx, self.show_chords && self.song.is_some(), |ui| {
                ui.add_space(6.0);
                ui.horizontal(|ui| {
                    ui.heading("Accord");
                    if ui.button("⏵").on_hover_text("Replier le panneau").clicked() {
                        collapse = true;
                    }
                });
                ui.separator();
                egui::ScrollArea::vertical().show(ui, |ui| {
                    match &panel_chords {
                        Some(((cur_name, cur_r, cur_m), next)) => {
                            ui.label(RichText::new("EN COURS").small().color(Color32::from_gray(140)));
                            notation::chord_diagram(ui, cur_name, *cur_r, *cur_m, true);
                            if let Some((n_name, n_r, n_m)) = next {
                                ui.add_space(10.0);
                                ui.label(RichText::new("SUIVANT").small().color(Color32::from_gray(140)));
                                notation::chord_diagram(ui, n_name, *n_r, *n_m, false);
                            }
                        }
                        None => {
                            ui.label("Aucun accord.");
                        }
                    }
                    ui.add_space(10.0);
                    ui.separator();
                    notation::finger_legend(ui);
                });
            });
        if collapse {
            self.show_chords = false;
        }

        // Left collapsible panel: the local (IndexedDB) song library.
        let mut load_lib: Option<(f64, String)> = None;
        let mut del_lib: Option<f64> = None;
        let mut commit_rename: Option<(f64, String)> = None;
        let mut start_rename: Option<(f64, String)> = None;
        // Filtered + sorted snapshot, so the closure doesn't borrow self.library.
        let view: Vec<LibEntry> = {
            let q = self.library_search.to_lowercase();
            let title_of = |e: &LibEntry| if e.title.is_empty() { e.name.clone() } else { e.title.clone() };
            let mut v: Vec<LibEntry> = self
                .library
                .iter()
                .filter(|e| {
                    q.is_empty()
                        || title_of(e).to_lowercase().contains(&q)
                        || e.style.to_lowercase().contains(&q)
                })
                .cloned()
                .collect();
            if self.library_sort_tempo {
                v.sort_by_key(|e| e.tempo);
            } else {
                v.sort_by_key(|e| title_of(e).to_lowercase());
            }
            v
        };
        egui::SidePanel::left("library_panel")
            .resizable(true)
            .default_width(245.0)
            .show_animated(ctx, self.show_library, |ui| {
                ui.add_space(6.0);
                ui.heading("📚 Bibliothèque");
                ui.label(
                    RichText::new("Stockée dans ce navigateur (hors-ligne).")
                        .small()
                        .color(Color32::from_gray(140)),
                );
                ui.horizontal(|ui| {
                    ui.label("🔎");
                    ui.add(
                        egui::TextEdit::singleline(&mut self.library_search)
                            .hint_text("rechercher…")
                            .desired_width(120.0),
                    );
                    ui.toggle_value(&mut self.library_sort_tempo, "tempo")
                        .on_hover_text("Trier par tempo (sinon par titre)");
                });
                ui.separator();
                if self.library.is_empty() {
                    ui.label(
                        RichText::new(
                            "Vide. Ouvrez un fichier puis « 💾 Ajouter », ou glissez-déposez des .MGU ici.",
                        )
                        .italics()
                        .color(Color32::from_gray(150)),
                    );
                }
                egui::ScrollArea::vertical().show(ui, |ui| {
                    for e in &view {
                        let title = if e.title.is_empty() { &e.name } else { &e.title };
                        ui.horizontal(|ui| {
                            if ui.button("▶").on_hover_text("Charger").clicked() {
                                load_lib = Some((e.id, e.name.clone()));
                            }
                            if ui.button("✏").on_hover_text("Renommer").clicked() {
                                start_rename = Some((e.id, title.clone()));
                            }
                            if ui.button("🗑").on_hover_text("Supprimer").clicked() {
                                del_lib = Some(e.id);
                            }
                            // Inline rename field for the selected entry.
                            match &mut self.renaming {
                                Some((rid, buf)) if *rid == e.id => {
                                    let r = ui.add(
                                        egui::TextEdit::singleline(buf).desired_width(110.0),
                                    );
                                    let go = ui.button("✓").clicked()
                                        || (r.lost_focus()
                                            && ui.input(|i| i.key_pressed(egui::Key::Enter)));
                                    if go {
                                        commit_rename = Some((e.id, buf.clone()));
                                    }
                                }
                                _ => {
                                    ui.vertical(|ui| {
                                        ui.label(RichText::new(title).strong());
                                        ui.label(
                                            RichText::new(format!(
                                                "{} · {} BPM · {}",
                                                if e.key.is_empty() { "?" } else { &e.key },
                                                e.tempo,
                                                if e.style.is_empty() { "—" } else { &e.style }
                                            ))
                                            .small()
                                            .color(Color32::from_gray(140)),
                                        );
                                    });
                                }
                            }
                        });
                        ui.separator();
                    }
                });
            });
        if let Some(pair) = start_rename {
            self.renaming = Some(pair);
        }
        if let Some((id, title)) = commit_rename {
            library::rename_song(id, title, self.library_inbox.clone(), ctx.clone());
            self.renaming = None;
        }
        if let Some((id, name)) = load_lib {
            library::load(id, name, self.inbox.clone(), ctx.clone());
        }
        if let Some(id) = del_lib {
            library::remove_song(id, self.library_inbox.clone(), ctx.clone());
        }

        egui::CentralPanel::default().show(ctx, |ui| {
            if let Some(err) = &self.error {
                ui.colored_label(Color32::from_rgb(200, 60, 50), err);
                ui.separator();
            }
            let Some(song) = &self.song else {
                ui.label("Ouvrez un fichier Band-in-a-Box pour commencer.");
                return;
            };

            // Header metadata (wrapped, so it never forces extra width — that
            // would resize the grid below).
            let header_rect = ui
                .horizontal_wrapped(|ui| {
                    ui.heading(if song.title.is_empty() {
                        "(sans titre)"
                    } else {
                        &song.title
                    });
                    ui.add_space(12.0);
                    ui.label(
                        RichText::new(format!(
                            "Ton : {}{}   ·   Tempo : {} BPM   ·   Style : {}",
                            parser::pitch_class_name(song.key_pc),
                            if song.key_minor { "m" } else { " majeur" },
                            song.tempo_bpm,
                            if song.style.is_empty() { "?" } else { &song.style }
                        ))
                        .color(Color32::from_gray(110)),
                    );
                })
                .response
                .rect;

            let structure = if song.form_bars > 0 {
                let loop_part = if song.choruses > 1 {
                    format!(
                        " · boucle mes. {}–{} × {} chœurs",
                        song.chorus_begin, song.chorus_end, song.choruses
                    )
                } else {
                    String::new()
                };
                format!("  ·  {} mes.{}", song.form_bars, loop_part)
            } else {
                String::new()
            };
            ui.label(
                RichText::new(format!(
                    "{}  —  {} notes de mélodie, {} accords{}",
                    self.file_name,
                    song.melody.len(),
                    song.chords.len(),
                    structure
                ))
                .small()
                .color(Color32::from_gray(130)),
            );
            ui.add_space(6.0);

            let tabs_rect = ui
                .horizontal(|ui| {
                    ui.selectable_value(&mut self.view, View::Chart, "🎼 Grille d'accords");
                    ui.selectable_value(&mut self.view, View::Staff, "𝄞 Partition");
                    ui.selectable_value(&mut self.view, View::Tab, "🎸 Tablature");
                    ui.separator();
                    ui.toggle_value(&mut self.show_chords, "🎸 Diagrammes");
                })
                .response
                .rect;

            // Big metronome beat number on the right, spanning the whole header
            // block (title line → tabs). Painted on a foreground layer so it
            // takes no layout space (the grid keeps its width) and nothing
            // overdraws it. Red on the downbeat.
            {
                let beats = 4u32;
                let beat = (current_tick / (TICKS_PER_BAR / beats)) % beats;
                let col = if !self.playing {
                    Color32::from_gray(110)
                } else if beat == 0 {
                    Color32::from_rgb(228, 55, 55)
                } else {
                    Color32::from_gray(220)
                };
                let top = header_rect.top();
                let bottom = tabs_rect.bottom();
                let cx = ui.max_rect().right() - 28.0;
                let painter = ui.ctx().layer_painter(egui::LayerId::new(
                    egui::Order::Foreground,
                    egui::Id::new("beat_counter"),
                ));
                painter.text(
                    egui::pos2(cx, (top + bottom) * 0.5),
                    egui::Align2::RIGHT_CENTER,
                    format!("{}", beat + 1),
                    egui::FontId::proportional((bottom - top).clamp(28.0, 110.0)),
                    col,
                );
            }
            ui.separator();

            // Thin playback progress bar over the whole song. Click to seek.
            {
                let total = (song.bars.max(1) as u32) * TICKS_PER_BAR;
                let frac = (current_tick as f32 / total as f32).clamp(0.0, 1.0);
                let (rect, presp) =
                    ui.allocate_exact_size(egui::vec2(ui.available_width(), 6.0), egui::Sense::click());
                let painter = ui.painter();
                painter.rect_filled(rect, 2.0, Color32::from_gray(55));
                let mut fill = rect;
                fill.set_width(rect.width() * frac);
                painter.rect_filled(fill, 2.0, Color32::from_rgb(60, 120, 230));
                if presp.clicked() {
                    if let Some(p) = presp.interact_pointer_pos() {
                        let f = ((p.x - rect.left()) / rect.width()).clamp(0.0, 1.0);
                        seek_tick = Some((f * total as f32) as u32);
                    }
                }
            }
            ui.add_space(4.0);

            if self.view == View::Chart && !song.chords.is_empty() {
                ui.label(
                    RichText::new(
                        "Accords décodés exactement du fichier : qualité, extensions (Maj7, 6, m7, 7…) \
                         et accords barrés (D/F#).",
                    )
                    .small()
                    .italics()
                    .color(Color32::from_gray(140)),
                );
            }

            let follow = self.playing; // auto-scroll only during playback
            egui::ScrollArea::both().show(ui, |ui| match self.view {
                View::Chart => {
                    if let Some(tick) = notation::chord_chart(ui, song, current_bar, follow) {
                        seek_tick = Some(tick);
                    }
                }
                View::Staff => notation::staff(ui, song, current_tick, follow),
                View::Tab => notation::tablature(ui, song, current_tick, follow),
            });
        });

        if let Some(tick) = seek_tick {
            // Debounce: absorb rapid repeated clicks on the same chord so we
            // don't pile up reschedules (which used to garble the audio).
            let now = ctx.input(|i| i.time);
            if now - self.last_seek_t > 0.10 {
                self.last_seek_t = now;
                self.seek_to_tick(tick);
            }
        }
    }
}
